package cz.cvut.fit.sabirdan.wework.domain.enumeration;

import java.util.Set;

public enum Authorization {
    SYSTEM_EDIT_USERS, SYSTEM_READ_PROJECTS, SYSTEM_INVITE, SYSTEM_EDIT_PROJECT_BASIC, SYSTEM_CHANGE_MEMBERSHIP_STATUS, SYSTEM_READ_INVITATIONS, SYSTEM_CHANGE_ROLE, SYSTEM_READ_TASKS, SYSTEM_CREATE_UPDATE_TASK, SYSTEM_DELETE_TASK , SYSTEM_CHANGE_PROJECT_STATUS, SYSTEM_DELETE_PROJECT,
    INVITE, KICK, EDIT_PROJECT_BASIC, DELETE_PROJECT, CHANGE_ROLE, CREATE_UPDATE_TASK, DELETE_TASK, CHANGE_PROJECT_STATUS;

    public static Set<Authorization> getAllSystemAuthorizations() {
        return Set.of(SYSTEM_EDIT_USERS, SYSTEM_READ_PROJECTS, SYSTEM_INVITE, SYSTEM_EDIT_PROJECT_BASIC, SYSTEM_CHANGE_MEMBERSHIP_STATUS, SYSTEM_READ_INVITATIONS, SYSTEM_CHANGE_ROLE, SYSTEM_READ_TASKS, SYSTEM_CREATE_UPDATE_TASK,  SYSTEM_DELETE_TASK, SYSTEM_CHANGE_PROJECT_STATUS, SYSTEM_DELETE_PROJECT);
    }

    public static Set<Authorization> getUserSystemRoleAuthorizations() {
        return Set.of();
    }

    public static Set<Authorization> getAllMemberAuthorizations() {
        return Set.of(INVITE, KICK, EDIT_PROJECT_BASIC, DELETE_PROJECT, CHANGE_ROLE, CREATE_UPDATE_TASK, DELETE_TASK, CHANGE_PROJECT_STATUS);
    }

    public static Set<Authorization> getMemberMemberRoleAuthorizations() {
        return Set.of(EDIT_PROJECT_BASIC, CREATE_UPDATE_TASK);
    }

    public static Set<Authorization> getAdminMemberRoleAuthorizations() {
        return Set.of(INVITE, KICK, EDIT_PROJECT_BASIC, CHANGE_ROLE, CREATE_UPDATE_TASK, DELETE_TASK, CHANGE_PROJECT_STATUS);
    }
}
