server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://172:18:0:2:5432/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
